[params]
title = "Patrick Pichler"
author = "Patrick Pichler"
mainSections = []
description = """
Interested in anything Kubernetes/Cloud/Linux related â˜ï¸
Linux nerd ğŸ§
"""
profilePicture = "images/profile_pic.jpg"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/patrickpichler/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/patrick-pichler-741a5a241/"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://infosec.exchange/@robotsanta"
