baseURL = 'https://patrickpichler.dev'
languageCode = 'en-us'
title = 'Patrick Pichler'
staticDir = ['static']

[params]
title = "Patrick Pichler"
author = "Patrick Pichler"
mainSections = []
description = """
Interested in anything Kubernetes/Cloud/Linux related â˜ï¸
Linux nerd ðŸ§
"""
profilePicture = "images/profile_pic.jpg"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/patrickpichler/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/patrick-pichler-741a5a241/"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://infosec.exchange/@robotsanta"

[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
identifier = "posts"
weight = 200
url = "/posts/"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
